org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true

# Разрешить путь с не-ASCII символами (кириллица в имени пользователя)
android.overridePathCheck=true

# Gradle запускаем через JDK из Android Studio (иначе в системе Java 8 — сборка падает).
org.gradle.java.home=C:\\Program Files\\Android\\Android Studio\\jbr
